# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_admin', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'administrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alum', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('ape_nom', models.CharField(max_length=70, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=8, null=True, unique=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiControlRecaudacionesAlumno',
            fields=[
                ('id_alum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('id_facultad', models.IntegerField()),
                ('ape_nom', models.CharField(max_length=70)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'api_control_recaudaciones_alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiControlRecaudacionesConcepto',
            fields=[
                ('id_concepto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=6)),
                ('concepto_a', models.CharField(max_length=6)),
                ('concepto_b', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'api_control_recaudaciones_concepto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiControlRecaudacionesRecaudacion',
            fields=[
                ('id_rec', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_alu', models.IntegerField()),
                ('id_concepto', models.IntegerField()),
                ('moneda', models.CharField(max_length=3)),
                ('numero_voucher', models.CharField(max_length=10)),
                ('importe', models.IntegerField()),
                ('carnet', models.CharField(max_length=30)),
                ('autoseguro', models.CharField(max_length=30)),
                ('ave', models.CharField(max_length=30)),
                ('devol_tran', models.CharField(max_length=30)),
                ('observacion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('flag_pago', models.BooleanField()),
            ],
            options={
                'db_table': 'api_control_recaudaciones_recaudacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id_concepto', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=6, unique=True)),
                ('concep_a', models.CharField(max_length=3)),
                ('concep_b', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'concepto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nom_curso', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id_dat_academicos', models.AutoField(primary_key=True, serialize=False)),
                ('mencion_grado', models.CharField(max_length=60)),
                ('centro_estudios', models.CharField(max_length=60)),
                ('pais_estudios', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'datos_academicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id_dia', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nom_dia', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directiva',
            fields=[
                ('id_direc', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'directiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('hr_inicio', models.CharField(max_length=2)),
                ('hr_fin', models.CharField(max_length=2)),
                ('tot_hrs', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'disponibilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nom_docente', models.CharField(max_length=50)),
                ('ape_docente', models.CharField(max_length=50)),
                ('codigo_docente', models.CharField(max_length=10)),
                ('dni_docente', models.CharField(max_length=8)),
                ('email_docente', models.CharField(max_length=70)),
                ('celular_docente', models.CharField(max_length=9)),
                ('genero', models.CharField(max_length=1)),
                ('pagina_web', models.CharField(max_length=50)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('fecha_nac', models.DateField()),
                ('pais', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('sunedu_le', models.CharField(max_length=2)),
                ('categoria', models.CharField(max_length=30)),
                ('regimen_dedicacion', models.CharField(max_length=30)),
                ('cv', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaAsesorDocente',
            fields=[
                ('id_exp_asesor_docente', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('universidad', models.CharField(max_length=80)),
                ('tesis', models.CharField(max_length=70)),
                ('tesista', models.CharField(max_length=70)),
                ('repositorio', models.CharField(max_length=70)),
                ('fecha_aceptacion', models.DateField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'experiencia_asesor_docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id_exp_laboral', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'experiencia_laboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'facultad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboralDocente',
            fields=[
                ('id_laboral_doc', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('universidad', models.CharField(max_length=80)),
                ('tipo_docente', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboral_docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_mod', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelesPrograma',
            fields=[
                ('id_niveles_program', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('pregrado', models.CharField(max_length=2)),
                ('maestria', models.CharField(max_length=2)),
                ('doctorado', models.CharField(max_length=2)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'niveles_programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id_preferencia', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'preferencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nom_programa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoInvestigacion',
            fields=[
                ('id_proyecto_invest', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('area_ocde', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto_investigacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recaudaciones',
            fields=[
                ('id_rec', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('moneda', models.CharField(blank=True, max_length=3, null=True)),
                ('numero_voucher', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('carnet', models.CharField(blank=True, max_length=30, null=True)),
                ('autoseguro', models.CharField(blank=True, max_length=30, null=True)),
                ('ave', models.CharField(blank=True, max_length=30, null=True)),
                ('devol_tran', models.CharField(blank=True, max_length=30, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('flag_pago', models.NullBooleanField()),
            ],
            options={
                'db_table': 'recaudaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoGrado',
            fields=[
                ('id_tip_grado', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nom_tip_grado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tipo_grado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tu', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=30)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accede',
            fields=[
                ('id_tu', models.ForeignKey(db_column='id_tu', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api_control_recaudaciones.TipoUsuario')),
            ],
            options={
                'db_table': 'accede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api_control_recaudaciones.Administrativo')),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
    ]
